### ISSUE TITLE
Is it only available in Linux OS?

### ISSUE THREAD

**Issue by SYZ2048** [contagon/AUVControl#3]
Hello, thank you for your great work. However, the package inekf seems only available on linux systems. May I ask if this code can only be used in the Linux system?

**Comment by contagon** [comment]
It's definitely only been tested on Linux systems (specifically Ubuntu). HoloOcean is compatible with Windows, so it should theoretically work for that as well.

Ahh, just realized you're referring to the inekf package. Yeah, it is Linux only.
